<?php
use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */
?>

<script>
    <?php // For some reason 'checkout:init:evaluation' is too late, so we use 'checkout:init:main' instead ?>
    window.addEventListener('checkout:init:main', event => {
        hyvaCheckout.evaluation.registerValidator('validateSantanderAcceptTos', async (element, component) => {
            return new Promise((resolve, reject) => {
                let currentAcceptTos = component.get('acceptTos');
                if (currentAcceptTos) {
                    resolve(true);
                } else {
                    reject(false);
                }
            });
        })
    })
</script>
<?php $hyvaCsp->registerInlineScript() ?>
